name: Verification of PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Verification of PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Build Tests with dotnet
        run: dotnet test --configuration Release --no-build

      - name: dotnet format
        run: dotnet format -v detailed --verify-no-changes