name: Secrets Workflow Demo

on:
  pull_request:
    branches: [ "main" ]

env:
  API_CSPROJ_PATH: "src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

jobs:
  secrets:
    name: Secrets Workflow Demo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment Variable
        run: echo "API SECRET KEY:" + ${{ secrets.SECRET_API_KEY }}
