name: CI/CD Workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  Deployment:
    name: Deploy ${{ inputs.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-actions-artifact
          path: final_artifacts/
          
      # Deploy to Azure Web apps
      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.APP_NAME }} # Replace with your app name
          package: final_artifacts/
